In [3]:
import numpy as np

In [7]:
cov_matrix = [[73.9865782, -40.21595603, 23.99233881],
              [-40.21595603, 543.93681368, -85.41264806],
              [23.99233881, -85.41264806, 47.06444247]]

cor_matrix = [[1., cov_matrix[0][1] / np.sqrt(cov_matrix[0][0]*cov_matrix[1][1]), 0.40658341],
              [cov_matrix[1][0] / np.sqrt(cov_matrix[0][0]*cov_matrix[1][1]), cov_matrix[1][1] / np.sqrt(cov_matrix[1][1]*cov_matrix[1][1]), -0.53382819],
              [0.40658341, -0.53382819, 1.]]

print('cov_matrix\n', np.array(cov_matrix))
print('cor_matrix\n', np.array(cor_matrix))

cov_matrix
 [[ 73.9865782  -40.21595603  23.99233881]
 [-40.21595603 543.93681368 -85.41264806]
 [ 23.99233881 -85.41264806  47.06444247]]
cor_matrix
 [[ 1.         -0.20046922  0.40658341]
 [-0.20046922  1.         -0.53382819]
 [ 0.40658341 -0.53382819  1.        ]]


In [8]:
trace = np.trace(cov_matrix)
trace

664.9878343500001